modify *_load

diff --git a/misc-modules/module_load b/misc-modules/module_load
--- a/misc-modules/module_load
+++ b/misc-modules/module_load
@@ -21,8 +21,15 @@ else
     group="wheel"
 fi
 
+kernel_ver=$(uname -r)
+module_dir="/lib/modules/$kernel_ver/updates"
+if [ ! -d "$module_dir" ]; then
+    echo "Module directory not found: $module_dir"
+    exit 1
+fi
+
 echo "Load our module, exit on failure"
-insmod ./$module.ko $* || exit 1
+insmod $module_dir//$module.ko $* || exit 1
 echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 if [ ! -z ${major} ]; then
diff --git a/scull/scull_load b/scull/scull_load
--- a/scull/scull_load
+++ b/scull/scull_load
@@ -11,9 +11,16 @@ else
     group="wheel"
 fi
 
+kernel_ver=$(uname -r)
+module_dir="/lib/modules/$kernel_ver/updates"
+if [ ! -d "$module_dir" ]; then
+    echo "Module directory not found: $module_dir"
+    exit 1
+fi
+
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
-insmod ./$module.ko $* || exit 1
+insmod $module_dir/$module.ko $* || exit 1
 
 # retrieve major number
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
